### ISSUE TITLE
Missing Synth. Dataset

### ISSUE THREAD

**Issue by brave-cattle** [wildphoton/RandConv#3]
Hello!
When trying to run the script, I found that the “synth” dataset doesn't seem to download automatically. And the link provided in the code comments is not working for me either. I had to run the code without this dataset for now, hope you can provide other ways to download the dataset.

**Comment by wildphoton** [comment]
Hi, the [link](https://drive.google.com/file/d/1ro-up5YDq1Cm9n_JaOG9pRbfPYVxcV8P/view) in the code is provided by the original author of the dataset and I have no problem to download it. Unfortunately, I don't think I can reshare it for copyright reasons. Can you double-check if you can access Google Drive in general?
